# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - devel
  - release
sudo: false
cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
  packages: true
warnings_are_errors: false
r_packages:
  - covr

install:
  - Rscript -e "renv::restore()"

after_success:
  - Rscript -e 'library(covr); codecov()'