on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: |
          renv::install()
          install.packages('pkgdown')
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL --no-multiarch --with-keep.source .

      - name: Build pkgdown site
        run: |
          pkgdown::build_site(new_process = FALSE)
        shell: Rscript {0}

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
        with:
          emptyCommits: false